Implemented circleci
Boschio/Final-Project pull request #19
Opened 2023-08-27 20:22 UTC by EfazAhmed

2023-08-27 21:18 UTC, ragogoe24 requested changes

2023-08-27 21:18 UTC, ragogoe24 commented on circleci/config.yml
> +          path: ~/CiCdDemo
path: ~/Final-Project

2023-08-28 01:13 UTC, Boschio commented
LGTM

2023-08-28 01:14 UTC, Boschio approved these changes
LGTM

2023-08-28 01:15 UTC, Boschio approved these changes
LGTM

2023-08-28 01:16 UTC, merged